### PR TITLE
Create symbolize-keys

### PR DESCRIPTION
**Pull request by josephinehall**
Just a little thing I looked up in pure Ruby vs in Rails the other day :3

### CODE REVIEW

**Comment by michaeltroy** [comment]
Ah looks nice Jojo.

**Comment by timriley** [comment]
You can also symbolize keys nicely if you're working in an app with the [transproc](https://github.com/solnic/transproc) gem available (like any of our Rodakase apps):

``` ruby
require "transproc/all"

module Functions
  extend Transproc::Registry

  import Transproc::HashTransformations
  import Transproc::ArrayTransformations

  def self.t(*args)
    self[*args]
  end
end

Functions.t(:symbolize_keys)[{"foo" => "bar"}]
# => {foo: "bar"}
```

Having a globally-available `Functions` module for basic hash and array data transformations is a pretty helpful thing, I think. And it means we can avoid complex-looking transformation logic in our own code :)

**Comment by timriley** [comment]
@josephinehall maybe that example is worth including too? And it might be worth mentioning that it's actually ActiveSupport that provides the `#symbolize_keys` monkey patch on `Hash`, which you get when you're working with Rails anyway :)

**Comment by josephinehall** [comment]
Yeah, I did use that function from transproc yesterday too! I'll add this information.

**Comment by josephinehall** [comment]
s/function/method :grimacing:

**Pull request merged**
