### PR TITLE
Add post about visually hidden labels.

### PR DESCRIPTION
**Pull request by andymccray**

### CODE REVIEW

**Comment by andymccray** [comment]
@makenosound, @timriley — happy for me to merge this one?

**Comment by timriley** [comment]
I'm no CSS-er, but I like this :)

**Comment by makenosound** [comment]
@andyicelab Yep, though I reckon you should add an [`aria-label`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute) in too!

**Comment by andymccray** [comment]
@makenosound Oh yeah!

I wonder if `aria-labelledby` would be a nicer technique. Something like:

``` slim
  ul.social-icons__list
   li.social-icons__list-item
     a.social-icons__anchor href="http://twitter.com/andymccray"
       span.social-icon__label--twitter.hide-visually Follow Andy McCray on Twitter
       i.fa.fa-twitter aria-labelledby="social-icon__label--twitter"
```

**Comment by makenosound** [comment]
@andyicelab Yep, totally legit too — I don’t think that implementation works though. `aria-labelledby` is supposed to reference an ID (or a series of hierarchical IDs):

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute

**Comment by andymccray** [comment]
Thanks @makenosound — have made a little update to the post body and those code snippets.

**Comment by andymccray** [comment]
Gonna merge this sucker unless anyone has any objections 👰 💒

**Comment by makenosound** [comment]
Do eet.

**Pull request merged**
